fenglin_fenglin_empty:
    path:     /
    defaults: { _controller: FenglinFenglinBundle:Default:empty }

fenglin_fenglin_homepage:
    path:     /consumer
    defaults: { _controller: FenglinFenglinBundle:Default:index }

fenglin_fenglin_shopper:
    path:     /shopper
    defaults: { _controller: FenglinFenglinBundle:Default:shopper }

fenglin_fenglin_consumer:
    path:     /consumer
    defaults: { _controller: FenglinFenglinBundle:Default:consumer }

fenglin_fenglin_rest:
    resource: "@FenglinFenglinBundle/Resources/config/routing/rest/refree.yml"
    prefix:   /rest