fenglin_fenglin_homepage:
    path:     /
    defaults: { _controller: FenglinFenglinBundle:Default:index }

fenglin_fenglin_shopper:
    path:     /shopper
    defaults: { _controller: FenglinFenglinBundle:Default:shopper }

fenglin_fenglin_consumer:
    path:     /consumer
    defaults: { _controller: FenglinFenglinBundle:Default:consumer }