panda_shopper_login:
    path:     /login
    defaults: { _controller: PandaShopperBundle:Default:login }

panda_shopper_rest:
    resource: "@PandaShopperBundle/Resources/config/routing/rest/shopper.yml"
    prefix:   /rest/
