panda_consumer_rest_index:
    path:     /{id}
    defaults: { _controller: PandaConsumerBundle:Rest/Consumer:index, id:0 }
    requirements:
        id: \d+
    options:
        expose: true

panda_consumer_rest_load_by_member_id:
    path:     /load-by-member-id/
    defaults: { _controller: PandaConsumerBundle:Rest/Consumer:loadByMemberId }
    options:
        expose: true

panda_consumer_rest_join_to_shopper:
    path:     /join-to-shopper
    defaults: { _controller: PandaConsumerBundle:Rest/Consumer:joinToShopper }
    options:
        expose: true