panda_staff:
    resource: "@PandaStaffBundle/Resources/config/routing.yml"
    prefix:   /staff

fenglin_login:
    resource: "@FenglinLoginBundle/Resources/config/routing.yml"
    prefix:   /login

fenglin_admin:
    resource: "@FenglinAdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

panda_mock_we_chat_o_auth:
    resource: "@PandaMockWeChatOAuthBundle/Resources/config/routing.yml"
    prefix:   /mock-wechat-oauth/

panda_we_chat:
    resource: "@PandaWeChatBundle/Resources/config/routing.yml"
    prefix:   /panda-we-chat/

panda_user:
    resource: "@PandaUserBundle/Resources/config/routing.yml"
    prefix:   /panda-user/

fenglin_fenglin:
    resource: "@FenglinFenglinBundle/Resources/config/routing.yml"
    prefix:   /

fenglin_cash_back:
    resource: "@FenglinCashBackBundle/Resources/config/routing.yml"
    prefix:   /fenglin-cash-back/

panda_consumer:
    resource: "@PandaConsumerBundle/Resources/config/routing.yml"
    prefix:   /panda-consumer/

panda_shopper:
    resource: "@PandaShopperBundle/Resources/config/routing.yml"
    prefix:   /panda-shopper/

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

