# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        in_memory:
#            memory: ~
       api_key_user_provider:
            id: api_key_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#
        main:
            pattern: ^/(panda-shopper|mock-wechat-oauth|panda-we-chat)
            security: false

        secured_area:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
            provider: api_key_user_provider

    access_control:
        - { path: ^/mock-wechat-oauth/, roles: ROLE_ANONYMOUSLY}
        - { path: ^/shopper, roles: ROLE_SHOPPER }
        - { path: ^/, roles: ROLE_CONSUMER }
        - { path: ^/, roles: ROLE_SHOPPER }


            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    encoders:
           Panda\ShopperBundle\Entity\Shopper:
               algorithm: md5