# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        in_memory:
#            memory: ~
       api_key_user_provider:
            id: api_key_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#
        main:
            pattern: ^/(panda-shopper|mock-wechat-oauth|panda-we-chat|login|panda-consumer\/read-qr|panda-consumer\/redirect-wechat-home-oa)
            security: false

        secured_area:
            pattern: ^/(shopper|staff|panda-consumer|fenglin-cash-back|panda-user|admin)
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
            provider: api_key_user_provider

    access_control:
        - { path: ^/mock-wechat-oauth/, roles: ROLE_ANONYMOUSLY }
        - { path: ^/login, roles: ROLE_ANONYMOUSLY }
        - { path: ^/shopper, roles: ROLE_SHOPPER }
        - { path: ^/staff/rest, roles: [ROLE_STAFF, ROLE_SHOPPER] }
        - { path: ^/panda-consumer/rest, roles: [ROLE_STAFF, ROLE_SHOPPER, ROLE_CONSUMER, ROLE_ADMIN] }
        - { path: ^/fenglin-cash-back/rest, roles: [ROLE_STAFF, ROLE_SHOPPER, ROLE_CONSUMER, ROLE_ADMIN] }

        - { path: ^/panda-user, roles: [ROLE_STAFF, ROLE_SHOPPER, ROLE_CONSUMER, ROLE_ADMIN] }
        - { path: ^/staff, roles: ROLE_STAFF }

        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: [ROLE_CONSUMER, ROLE_SHOPPER] }


            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    encoders:
           Panda\ShopperBundle\Entity\Shopper:
               algorithm: md5
           Panda\StaffBundle\Entity\Staff:
               algorithm: md5
           Fenglin\AdminBundle\Entity\Admin:
               algorithm: md5