<?php

namespace Panda\ShopperBundle\Repository;

/**
 * ShopperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopperRepository extends \Doctrine\ORM\EntityRepository
{
}
