<?php

namespace Fenglin\FenglinBundle\Repository;

/**
 * AuthorizationLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorizationLogRepository extends \Doctrine\ORM\EntityRepository
{
}
