<?php

namespace Fenglin\FenglinBundle\Repository;

use Fenglin\FenglinBundle\Entity\ConsumerAmount;

/**
 * ConsumerAmountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsumerAmountRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $shopper
     * @param $consumer
     * @return ConsumerAmount|null|object
     */
    public function createIfNotExist($shopper, $consumer)
    {
        $consumerAmount = $this->findOneBy([
            'shopper'   => $shopper,
            'consumer'  => $consumer
        ]);

        if (!$consumerAmount) {
            $consumerAmount = new ConsumerAmount();
            $consumerAmount->setShopper($shopper);
            $consumerAmount->setConsumer($consumer);
            $consumerAmount->setTotalAmount(0);
            $this->_em->persist($consumerAmount);
            $this->_em->flush();
        }

        return $consumerAmount;
    }
}
