<?php

namespace Fenglin\FenglinBundle\Repository;

/**
 * ConsumerUseCashBackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsumerUseCashBackRepository extends \Doctrine\ORM\EntityRepository
{
}
