<?php

namespace Fenglin\FenglinBundle\Repository;

/**
 * ConsumerAmountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsumerAmountRepository extends \Doctrine\ORM\EntityRepository
{
}
