<?php

namespace Fenglin\FenglinBundle\Repository;

/**
 * InviteFriendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InviteFriendRepository extends \Doctrine\ORM\EntityRepository
{
}
