<?php

namespace Fenglin\FenglinBundle\Repository;

/**
 * RefreeTreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefreeTreeRepository extends \Doctrine\ORM\EntityRepository
{
}
