Panda\UserBundle\Entity\RequestRecoveryPassword:
    type: entity
    table: user_requests_recovery_password
    repositoryClass: Panda\UserBundle\Repository\RequestRecoveryPasswordRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
        dateExpired:
            type: datetime
            column: date_expired
        used:
            type: boolean
        hash:
            type: text
    manyToOne:
        user:
            targetEntity: User
            inversedBy: requestsRecoveryPassword
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
