Panda\StaffBundle\Entity\Staff:
    type: entity
    table: panda_staff
    repositoryClass: Panda\StaffBundle\Repository\StaffRepository

    fields:
        name:
            type: string
            length: 255
    manyToOne:
        shopper:
            targetEntity: \Panda\ShopperBundle\Entity\Shopper
            inversedBy: staffs
            joinColumn:
                name: shopper_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
