fenglin_cash_back_rest_index:
    path:     /{id}
    defaults: { _controller: FenglinCashBackBundle:Rest/CashBack:index, id:0 }
    requirements:
        id: \d+
    options:
        expose: true

fenglin_cash_back_rest_list:
    path:     /list
    defaults: { _controller: FenglinCashBackBundle:Rest/CashBack:list }
    options:
        expose: true