fenglin_cash_back_rest_index:
    path:     /{id}
    defaults: { _controller: FenglinCashBackBundle:Rest/CashBack:index, id:0 }
    requirements:
        id: \d+
    options:
        expose: true

fenglin_cash_back_rest_list:
    path:     /list
    defaults: { _controller: FenglinCashBackBundle:Rest/CashBack:list }
    options:
        expose: true

fenglin_cash_back_rest_confirm_cash_back:
    path:     /confirm-cash-back/{id}
    defaults: { _controller: FenglinCashBackBundle:Rest/CashBack:confirmCashBack }
    requirements:
        id: \d+
    options:
        expose: true

fenglin_cash_back_rest_confirm_cash_back_list:
    path:     /confirm-cash-back/list
    defaults: { _controller: FenglinCashBackBundle:Rest/CashBack:confirmCashBackList }
    options:
        expose: true