#panda_shopper_rest_index:
#    path:     /{id}
#    defaults: { _controller: PandaShopperBundle:Rest/Shopper:index, id:0 }
#    requirements:
#        id: \d+
#    options:
#        expose: true
#

panda_shopper_qr_rest_ticket:
    path:     /ticket
    defaults: { _controller: PandaShopperBundle:Rest/ShopperQR:getTicket }
    options:
        expose: true

