panda_shopper_rest_index:
    path:     /{id}
    defaults: { _controller: PandaShopperBundle:Rest/Shopper:index, id:0 }
    requirements:
        id: \d+
    options:
        expose: true

panda_shopper_rest_list:
    path:     /list/{page}
    defaults: { _controller: PandaShopperBundle:Rest/Shopper:list, page:1 }
    requirements:
        page: \d+
    options:
        expose: true

panda_shopper_rest_cash_back_list:
    path:     /cash-back-list/{page}
    defaults: { _controller: PandaShopperBundle:Rest/Shopper:cashBackList, page:1 }
    requirements:
        page: \d+
    options:
        expose: true

panda_shopper_rest_upload:
    path:     /upload-image
    defaults: { _controller: PandaShopperBundle:Rest/Shopper:uploadImage }
    requirements:
        id: \d+
    options:
        expose: true

#loadByName
panda_shopper_rest_load_by_name:
    path:     /load-by-name
    defaults: { _controller: PandaShopperBundle:Rest/Shopper:loadByName }
    options:
        expose: true

#loadCurrentShopper
panda_shopper_rest_load_current_shopper:
    path:     /load-current-shopper
    defaults: { _controller: PandaShopperBundle:Rest/Shopper:loadCurrent }
    options:
        expose: true
