<?php

namespace Fenglin\CashBackBundle\Repository;

/**
 * CashBackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CashBackRepository extends \Doctrine\ORM\EntityRepository
{
}
