<?php

namespace Fenglin\CashBackBundle\Repository;

/**
 * CashBackLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CashBackLogRepository extends \Doctrine\ORM\EntityRepository
{
}
