<?php

namespace Panda\UserBundle\Repository;

/**
 * RequestRecoveryPasswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestRecoveryPasswordRepository extends \Doctrine\ORM\EntityRepository
{
}
